[package]
name = "drizzle"
version = "0.1.0"
authors = ["Leo Ring <leoring03@gmail.com>"]
edition = "2024"
publish = false
# rust-version = "1.92"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }   # UM, ACTUALLY
nursery = { level = "deny", priority = -1 }    # BETA LINTS
# DENY PANICS
unwrap_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
must_use_candidate = "allow"
missing_errors_doc = "allow"
too_many_lines = "allow"

[profile.release]
lto = true

[dependencies]
chrono = "0.4.45"
gettext-rs = { version = "0.7.7", features = ["gettext-system"] }
relm4 = { version = "0.11.0", features = ["libadwaita", "gnome_49"] }
relm4-icons = "0.11.0"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[build-dependencies]
relm4-icons-build = "0.11"
